camel:
  main:
    name: MyCamel

    # keep Camel running
    run-controller: true

    # verbose summary so you can see the pairing of routes and routes configurations
    startup-summary-level: verbose

    # which directory(s) to scan for routes/route-configurations which can be xml, yaml or java files
    routes-include-pattern: classpath:timers/*,classpath:rest-rest/*

app:
  specificProcessorConfig: dummyText
  externalAppUrl: http://localhost:8080/external